apiVersion: v1
kind: Pod
metadata:
  name: todapppod
  labels:
    app.kubernetes.io/name: todoapp
spec:
  containers:
  - name: todocontainer
    image: nginx
    
    ports:
      - containerPort: 80
