apiVersion: v1
kind: Service
metadata:
  name: myservive
  labels:
    app.kubernetes.io/name: todoapp 
spec:
  selector:
    app.kubernetes.io/name: todoapp
  ports:
  - port: 8081
    targetPort: 80
